Fix building mkdtimg against musl
Fix building mkdtimg against musl libc by fixing a -Wformat error
that is not caught by glibc because glibc's fprintf is not annotated
with the __printf__ attribute:
system/libufdt/utils/src/mkdtimg_dump.c:92:21: error: flag '+' results in undefined behavior with 's' conversion specifier [-Werror,-Wformat]
  fprintf(out_fp, "%+20s = %d\n", name, fdt32_to_cpu(value));

Bug: 190084016
Test: m USE_HOST_MUSL=true mkdtimg
Change-Id: Ibcb5a8839cc3c220789927a7eeffce162fb21613